name: GitHub Actions Tests
on: [pull_request]

jobs:
  build:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '17.8.0'

      - run: npm ci

      - run: npm test
        env:
          CI: true